### ISSUE TITLE
Missing variable name

### ISSUE THREAD

**Issue by ColinH** [MagicLemma/apecs#10]
Line 573, which is in member function `registry<Comps...>::view()`, currently reads

```
            apx::entity = d_entities[index];
```

which I needed to change to

```
            apx::entity entity = d_entities[index];
```

in order to make it compile (with GCC10).

**Comment by fullptr** [comment]
Whoops, I though I had a test covering this but it looks like I didn't, sure enough this fails when I add one. This project was born out of another side project of mine which is currently using a precursor to this, no doubt this would have been caught if I had switched that project to using apecs, which I will be doing soon.

Thanks!
