### ISSUE TITLE
Incorrect use of move

### ISSUE THREAD

**Issue by ColinH** [MagicLemma/apecs#11]
In member function `registry<Comps...>::add(apx::entity entity, Comp&& component)` the argument `component` is passed on with `std::move()` even though `Comp` could be `some_component_type&`.

Since `emplace()` does it correctly you probably know that you just need to use `std::forward` instead, and can then remove the other overload of `add()`, the one with the `const Comp&`.

**Comment by fullptr** [comment]
I suspect I may have gotten away with this, since if I passed a `some_component_type&` it would have been handled by the `registry<Comps...>::add(apx::entity entity, const Comp& component)` overload? Nevertheless this is a very nice simplification.

**Comment by ColinH** [comment]
> it would have been handled by the registry<Comps...>::add(apx::entity entity, const Comp& component) overload?

Unfortunately (?) not, it chooses the other overload. It can be slightly annoying because the overload resolution between `const foo&` and `foo&&` behaves differently depending on whether `foo` is a template parameter or not, so one also has to be extra careful when refactoring code and transforming back or forth between a function and a function template...

```
colin@magic:/tmp/ramdisk> cat t.cpp 
#include <string>
#include <iostream>

struct foo
{
   template< typename T >
   int bar( T&& )
   {
      std::cerr << "+++" << std::endl;
      std::cerr << __PRETTY_FUNCTION__ << std::endl;
      return 1;
   }

   template< typename T >
   int bar( const T& )
   {
      std::cerr << "---" << std::endl;
      std::cerr << __PRETTY_FUNCTION__ << std::endl;
      return 2;
   }
};

int main()
{
   foo f;
   std::string a;
   const std::string b;
   return f.bar( a ) + f.bar( std::move( a ) ) + f.bar( b );
}
colin@magic:/tmp/ramdisk> clang++ -Wall -Wextra -O3 -pedantic -std=c++17 t.cpp 
colin@magic:/tmp/ramdisk> ./a.out 
+++
int foo::bar(T &&) [T = std::__1::basic_string<char> &]
+++
int foo::bar(T &&) [T = std::__1::basic_string<char>]
---
int foo::bar(const T &) [T = std::__1::basic_string<char>]
```

**Comment by fullptr** [comment]
Ahh I see, that example makes it very clear, thanks!
