### ISSUE TITLE
Missing template keyword

### ISSUE THREAD

**Issue by ColinH** [MagicLemma/apecs#9]
Hi, really like the minimalist approach of apecs!

I just tried compiling with GCC10 and stumbled over the following issue:

In template class `handle` the type of member field `registry` depends on the template parameters of `handle`.

In the member functions of `handle` that call `registry->function<Comp>(...)` it is therefore necessary to use the `template` keyword as in `registry->template function<Comp>(...)`.

**Comment by fullptr** [comment]
Hey, first of all thank you for reviewing my project, it is much appreciated!

This is really interesting, I'm currently only running on Windows but I do plan to compile it with gcc and clang in WSL, so thank you for pointing this out, I'll be making this change shortly.
